//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "configuration_key_reference_audit")]
pub struct Model {
    pub id: Option<i32>,
    pub name: Option<String>,
    pub description: Option<String>,
    pub type_id: Option<i32>,
    pub optional: Option<bool>,
    pub allows_multiple: Option<bool>,
    pub allows_user_override: Option<bool>,
    pub deactivate_timestamp: Option<DateTime>,
    #[sea_orm(primary_key)]
    pub audit_id: i32,
    pub audit_action: String,
    pub audit_timestamp_transaction_start: DateTime,
    pub audit_timestamp_statement_start: DateTime,
    pub audit_timestamp_trigger: DateTime,
    pub audit_client_host: String,
    pub audit_client_port: i32,
    pub audit_client_query: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
