//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "configuration_type_reference")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::configuration_reference::Entity")]
    ConfigurationReference,
}

impl Related<super::configuration_reference::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConfigurationReference.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
