/* tslint:disable */
/* eslint-disable */
/**
 * Prelude API
 * Primary REST API for Prelude
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: sophie@sophiekatz.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConfigurationTypeResponse } from './ConfigurationTypeResponse';
import {
    ConfigurationTypeResponseFromJSON,
    ConfigurationTypeResponseFromJSONTyped,
    ConfigurationTypeResponseToJSON,
} from './ConfigurationTypeResponse';

/**
 * A set of configuration types
 * @export
 * @interface ConfigurationTypeSetResponse
 */
export interface ConfigurationTypeSetResponse extends Array<ConfigurationTypeResponse> {
}

/**
 * Check if a given object implements the ConfigurationTypeSetResponse interface.
 */
export function instanceOfConfigurationTypeSetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConfigurationTypeSetResponseFromJSON(json: any): ConfigurationTypeSetResponse {
    return ConfigurationTypeSetResponseFromJSONTyped(json, false);
}

export function ConfigurationTypeSetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationTypeSetResponse {
    return json;
}

export function ConfigurationTypeSetResponseToJSON(value?: ConfigurationTypeSetResponse | null): any {
    return value;
}

