/* tslint:disable */
/* eslint-disable */
/**
 * Prelude API
 * Primary REST API for Prelude
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: sophie@sophiekatz.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConfigurationKeyResponse } from './ConfigurationKeyResponse';
import {
    ConfigurationKeyResponseFromJSON,
    ConfigurationKeyResponseFromJSONTyped,
    ConfigurationKeyResponseToJSON,
} from './ConfigurationKeyResponse';

/**
 * A set of configuration keys
 * @export
 * @interface ConfigurationKeySetResponse
 */
export interface ConfigurationKeySetResponse extends Array<ConfigurationKeyResponse> {
}

/**
 * Check if a given object implements the ConfigurationKeySetResponse interface.
 */
export function instanceOfConfigurationKeySetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConfigurationKeySetResponseFromJSON(json: any): ConfigurationKeySetResponse {
    return ConfigurationKeySetResponseFromJSONTyped(json, false);
}

export function ConfigurationKeySetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationKeySetResponse {
    return json;
}

export function ConfigurationKeySetResponseToJSON(value?: ConfigurationKeySetResponse | null): any {
    return value;
}

