/* tslint:disable */
/* eslint-disable */
/**
 * Portobello API
 * Primary REST API for Portobello
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: sophie@sophiekatz.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConfigurationEntryItemResponse } from './ConfigurationEntryItemResponse';
import {
    ConfigurationEntryItemResponseFromJSON,
    ConfigurationEntryItemResponseFromJSONTyped,
    ConfigurationEntryItemResponseToJSON,
} from './ConfigurationEntryItemResponse';

/**
 * A set of configuration entry items
 * 
 * **NOTE:** `id` values may not be in order because order is stored in an implementation specific way.
 * @export
 * @interface ConfigurationEntryItemSetResponse
 */
export interface ConfigurationEntryItemSetResponse extends Array<ConfigurationEntryItemResponse> {
}

/**
 * Check if a given object implements the ConfigurationEntryItemSetResponse interface.
 */
export function instanceOfConfigurationEntryItemSetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConfigurationEntryItemSetResponseFromJSON(json: any): ConfigurationEntryItemSetResponse {
    return ConfigurationEntryItemSetResponseFromJSONTyped(json, false);
}

export function ConfigurationEntryItemSetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationEntryItemSetResponse {
    return json;
}

export function ConfigurationEntryItemSetResponseToJSON(value?: ConfigurationEntryItemSetResponse | null): any {
    return value;
}

