/* tslint:disable */
/* eslint-disable */
/**
 * Portobello API
 * Primary REST API for Portobello
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: sophie@sophiekatz.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A type for the data stored in a configuration key
 * @export
 * @interface ConfigurationTypeResponse
 */
export interface ConfigurationTypeResponse {
    /**
     * A unique id for the object
     * @type {number}
     * @memberof ConfigurationTypeResponse
     */
    id: number;
    /**
     * A human-readable name for the object
     * @type {string}
     * @memberof ConfigurationTypeResponse
     */
    name: string;
    /**
     * A human-readable description of the object
     * @type {string}
     * @memberof ConfigurationTypeResponse
     */
    description: string;
}

/**
 * Check if a given object implements the ConfigurationTypeResponse interface.
 */
export function instanceOfConfigurationTypeResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function ConfigurationTypeResponseFromJSON(json: any): ConfigurationTypeResponse {
    return ConfigurationTypeResponseFromJSONTyped(json, false);
}

export function ConfigurationTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationTypeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function ConfigurationTypeResponseToJSON(value?: ConfigurationTypeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
    };
}

