# MIT License
#
# Copyright (c) 2023 Sophie Katz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "3.9"

services:
  # Development container for VS Code to use
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Command required by VS Code to keep the container running during development
    command: /bin/sh -c "while sleep 1000; do :; done"
    # Mount project directory as a volume
    volumes:
      - ../:/app:cached
    # Loosen security requirements to allow for debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # Set update tag
    environment:
      # Versions of images used in this file
      - PORTOBELLO_POSTGRES_VERSION_LAST_UPDATED=2023-02-18
      - PORTOBELLO_PGADMIN4_VERSION_LAST_UPDATED=2023-02-18
      - PORTOBELLO_KEYCLOAK_VERSION_LAST_UPDATED=2023-02-18

  # Database container
  db:
    # When updating this version, make sure to also update the *_LAST_UPDATED
    # date so that out-of-date dependencies can be tracked.
    image: postgres:15.1-alpine
    env_file:
      - ../.env
    ports:
      - "9002:5432"
    volumes:
      - db:/var/lib/postgresql/data:cached
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d:cached

  # Database client
  db_client:
    # When updating this version, make sure to also update the *_LAST_UPDATED
    # date so that out-of-date dependencies can be tracked.
    image: dpage/pgadmin4:6.20
    env_file:
      - ../.env
    ports:
      - "9004:80"
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json:cached

  # Authentication service container
  auth:
    # When updating this version, make sure to also update the *_LAST_UPDATED
    # date so that out-of-date dependencies can be tracked.
    image: quay.io/keycloak/keycloak:20.0.3
    env_file:
      - ../.env
    ports:
      - "9003:8080"
    command: start-dev --import-realm
    volumes:
      - ./keycloak-import:/opt/keycloak/data/import
      - auth:/opt/keycloak/data:cached

volumes:
  db:
    driver: local
  auth:
    driver: local
